config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :receptions
  resources :delivered_orders
  resources :custmer_client_addresses
  resources :customer_clients
  resources :countries do
    resources :regions do 
      resources :communes
    end
  end
  get 'reports/warehouse', to: "reports#warehouse", as: "warehouse_report"
  get 'reports/weekly_delivered_orders', to: "reports#weekly_delivered_orders", as: "weekly_delivered_orders_report"
  resources :stocks
  resources :warehouse_locations
  resources :warehouses
	root to: "products#sku_finder"

  ##imports
  post "import_customers", to: "customers#import_agunsa_customers", as: "import_agunsa_customers"
  post "import_agunsa_products", to: "products#import_agunsa_products", as: "import_agunsa_products"
  post "import_agunsa_warehouses", to: "warehouses#import_agunsa_warehouses", as: "import_agunsa_warehouses"
  post "import_agunsa_warehouse_locations", to: "warehouse_locations#import_agunsa_warehouse_locations", as: "import_agunsa_warehouse_locations"
  post "import_agunsa_stock", to: "stocks#import_agunsa_stock", as: "import_agunsa_stock"
  post "import_agunsa_delivered_orders", to: "delivered_orders#import_agunsa_delivered_orders", as: "import_agunsa_delivered_orders"
  post "import_agunsa_receptions", to: "receptions#import_agunsa_receptions", as: "import_agunsa_receptions"

  resources :products

  resources :customers do
  	collection do
  	end
  end

  get "sku_finder", to: "products#sku_finder", as: "sku_finder"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reception.rb
class Reception < ApplicationRecord
  include Sidekiq::Worker
  belongs_to :customer
  belongs_to :warehouse
  has_many :reception_products




  def self.import_agunsa_receptions(customer)
    #customer = Customer.find(customer_id)
    receptions_info = AgunsaManager::GetReceptions.call(customer.client_code, customer.receptions.last.present? ? customer.receptions.last.reception_number : nil )
    warehouses = customer.warehouses
    puts receptions_info.count
    
    i = 1
    while i <= receptions_info.count do
      reception_items = []
      reception_items.push(receptions_info[i-1])
      while ( i < receptions_info.count && receptions_info[i]['numero_re'] == reception_items.last['numero_re'] )  do
        reception_items.push(receptions_info[i])
        i = i+1
      end
      Reception.create_with_childs(reception_items, customer, warehouses)
      i = i+1
    end
  end


  def self.create_with_childs(reception_items, customer, warehouses)
    warehouse = warehouses.select{ |warehouse| warehouse.name == reception_items[0]['codigo_bodega'] }.first

    if( Reception.where({ customer: customer, reception_number: reception_items[0]['numero_re'].to_i }).empty? )
      reception = Reception.create({
        customer: customer,
        warehouse: warehouse,
        reception_number: reception_items[0]['numero_re'],
        rrp_number: reception_items[0]['numero_rrp'],
        guia_aga_o_fa: reception_items[0]['guia_aga_o_fa'],
        customer_reference_document: reception_items[0]['documento_referencia_cliente'],
        recepcion_backup_document: reception_items[0]['documento_respaldo_re'],
        start_unload: reception_items[0]['fecha_inicio_descarga'],
        finish_unload: reception_items[0]['fecha_termino_descarga'],
        digitation_date: reception_items[0]['fecha_digitacion'],
        origin: reception_items[0]['origen'],
        recepcion_order_number: reception_items[0]['numero_orden_recepcion'],
        reception_observation: reception_items[0]['Observaciones_RE'],
        rrp_observation: reception_items[0]['Observaciones_RRP'],
        reception_order_observation: reception_items[0]['Observaciones_OR'],
        container_seal: reception_items[0]['Sello_contenedor'],
        recepcion_order_date: reception_items[0]['fecha_orden_recepcion'],
        reception_order_backup_document: reception_items[0]['documento_respaldo_or'],
        ctnr_code: reception_items[0]['codigo_CTNR']

      })
      products_array = []
      reception_items.each do |reception_info|
        products_array.push(
          {
            reception_id: reception.id,
            product_id: customer.products.where("product_code ILIKE ?", "%#{reception_info['codigo_producto'].tr(" ","")}%").first.id,
            quantity: reception_info['cantidad_entrada_producto'].to_i,
            lot_code: reception_info['codigo_lote'].tr(" ",""),
            updated_at: DateTime.now,
            created_at: DateTime.now
          }
        )
      end
      ##we inser products to delivered order
      ReceptionProduct.insert_all!(products_array)

    else
      puts "Already Exists"
    end

  end
  
end

app/controllers/receptions_controller.rb
class ReceptionsController < ApplicationController
  before_action :set_reception, only: [:show, :edit, :update, :destroy]

  # GET /receptions
  # GET /receptions.json
  def index
    @receptions = Reception.all
    @receptions = @receptions.where(customer_id: params[:customer_id]) if params[:customer_id].present?
    @receptions = @receptions.where("rrp_number = #{params[:rrp]}") if params[:rrp].present?
    @receptions = @receptions.where("reception_number = #{params[:re]}") if params[:re].present?
    @receptions = @receptions.where("recepcion_order_number = #{params[:or]}") if params[:or].present?
    @receptions = @receptions.where("recepcion_backup_document ILIKE ?", "%"+params[:backup_document]+"%") if params[:backup_document].present?

    @receptions = @receptions.order(reception_number: :desc).paginate(page: params[:page], per_page: 50)
  end

  # GET /receptions/1
  # GET /receptions/1.json
  def show
    @reception_products = @reception.reception_products
  end

  # GET /receptions/new
  def new
    @reception = Reception.new
  end

  # GET /receptions/1/edit
  def edit
  end

  # POST /receptions
  # POST /receptions.json
  def create
    @reception = Reception.new(reception_params)

    respond_to do |format|
      if @reception.save
        format.html { redirect_to @reception, notice: 'Reception was successfully created.' }
        format.json { render :show, status: :created, location: @reception }
      else
        format.html { render :new }
        format.json { render json: @reception.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receptions/1
  # PATCH/PUT /receptions/1.json
  def update
    respond_to do |format|
      if @reception.update(reception_params)
        format.html { redirect_to @reception, notice: 'Reception was successfully updated.' }
        format.json { render :show, status: :ok, location: @reception }
      else
        format.html { render :edit }
        format.json { render json: @reception.errors, status: :unprocessable_entity }
      end
    end
  end

  def import_agunsa_receptions
    @customer = Customer.find(params[:customer_id])
    Reception.import_agunsa_receptions(@customer)
  end

  # DELETE /receptions/1
  # DELETE /receptions/1.json
  def destroy
    @reception.destroy
    respond_to do |format|
      format.html { redirect_to receptions_url, notice: 'Reception was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reception
      @reception = Reception.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reception_params
      params.require(:reception).permit(:customer_id, :warehouse_id, :rrp_number, :guia_aga_o_fa, :customer_reference_document, :recepcion_backup_document, :start_unload, :finish_unload, :digitation_date, :reception_number, :origin, :recepcion_order_number, :reception_observation, :rrp_observation, :reception_order_observation, :container_seal, :recepcion_order_date, :reception_order_backup_document, :ctnr_code)
    end
end

app/helpers/receptions_helper.rb
module ReceptionsHelper
end

app/views/receptions/_form.html.erb
<%= form_with(model: reception, local: true) do |form| %>
  <% if reception.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reception.errors.count, "error") %> prohibited this reception from being saved:</h2>

      <ul>
        <% reception.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :warehouse_id %>
    <%= form.text_field :warehouse_id %>
  </div>

  <div class="field">
    <%= form.label :rrp_number %>
    <%= form.number_field :rrp_number %>
  </div>

  <div class="field">
    <%= form.label :guia_aga_o_fa %>
    <%= form.number_field :guia_aga_o_fa %>
  </div>

  <div class="field">
    <%= form.label :customer_reference_document %>
    <%= form.text_field :customer_reference_document %>
  </div>

  <div class="field">
    <%= form.label :recepcion_backup_document %>
    <%= form.text_field :recepcion_backup_document %>
  </div>

  <div class="field">
    <%= form.label :start_unload %>
    <%= form.datetime_select :start_unload %>
  </div>

  <div class="field">
    <%= form.label :finish_unload %>
    <%= form.datetime_select :finish_unload %>
  </div>

  <div class="field">
    <%= form.label :digitation_date %>
    <%= form.datetime_select :digitation_date %>
  </div>

  <div class="field">
    <%= form.label :reception_number %>
    <%= form.number_field :reception_number %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <%= form.label :recepcion_order_number %>
    <%= form.number_field :recepcion_order_number %>
  </div>

  <div class="field">
    <%= form.label :reception_observation %>
    <%= form.text_field :reception_observation %>
  </div>

  <div class="field">
    <%= form.label :rrp_observation %>
    <%= form.text_field :rrp_observation %>
  </div>

  <div class="field">
    <%= form.label :reception_order_observation %>
    <%= form.text_field :reception_order_observation %>
  </div>

  <div class="field">
    <%= form.label :container_seal %>
    <%= form.text_field :container_seal %>
  </div>

  <div class="field">
    <%= form.label :recepcion_order_date %>
    <%= form.datetime_select :recepcion_order_date %>
  </div>

  <div class="field">
    <%= form.label :reception_order_backup_document %>
    <%= form.text_field :reception_order_backup_document %>
  </div>

  <div class="field">
    <%= form.label :ctnr_code %>
    <%= form.number_field :ctnr_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receptions/edit.html.erb
<h1>Editing Reception</h1>

<%= render 'form', reception: @reception %>

<%= link_to 'Show', @reception %> |
<%= link_to 'Back', receptions_path %>

app/views/receptions/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Inicio', root_path %></li>
    <li class="breadcrumb-item active">Recepciones</li>
  </ol>
</nav>


<p id="notice"><%= notice %></p>

<h2>Recepciones</h2>

<%= form_tag(receptions_path, method: :get) do %>
  <div class="row">
    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
      <%= select_tag 'customer_id', options_for_select(Customer.all.order(name: :asc).collect{ |u| [u.name, u.id] }, selected: params[:customer_id]), :prompt => "TODOS", class: "form-control" %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
      <%= number_field_tag 're', params[:re], placeholder: "RE", class: "form-control" %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
      <%= number_field_tag 'rrp', params[:rrp], placeholder: "RRP", class: "form-control" %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
      <%= number_field_tag 'or', params[:or], placeholder: "OR", class: "form-control" %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
      <%= text_field_tag 'backup_document', params[:backup_document], placeholder: "Doc Respaldo", class: "form-control" %>
    </div>


  </div>
  <div class="row">
    <div class="col-6">
      <%= submit_tag "BUSCAR", class:"btn btn-sm btn-info" %>
    </div>
  </div>
<br>
<% end %>


<div class="table-responsive">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Warehouse</th>
      <th>Recepcion</th>
      <th>RRP</th>
      <th>OR</th>
      <th>Lineas</th>
      <th>Items</th>
      <th>Documento Ref Cliente</th>
      <th>Respaldo Re</th>
      <th>Inicio Descarga</th>
    </tr>
  </thead>

  <tbody>
    <% @receptions.each do |reception| %>
      <tr>
        <td><%= link_to reception.customer.client_code, customer_path(reception.customer) %></td>
        <td><%= link_to reception.warehouse.name, warehouse_path(reception.warehouse) %></td>
        <td><%= link_to reception.reception_number, reception_path(reception) %></td>
        <td><%= link_to reception.rrp_number, reception_path(reception) %></td>
        <td><%= link_to reception.recepcion_order_number, reception_path(reception) %></td>
        <td><%= reception.reception_products.count %></td>
        <td><%= reception.reception_products.sum(:quantity) %></td>
        <td><%= reception.customer_reference_document %></td>
        <td><%= reception.recepcion_backup_document %></td>
        <td><%= reception.start_unload %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<div class="row">
  <div class="col">
    <%= will_paginate @products %>
  </div>
</div>

app/views/receptions/new.html.erb
<h1>New Reception</h1>

<%= render 'form', reception: @reception %>

<%= link_to 'Back', receptions_path %>

app/views/receptions/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Inicio', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Recepciones', receptions_path %></li>
    <li class="breadcrumb-item active"><%= @reception.reception_number %></li>
  </ol>
</nav>

<p id="notice"><%= notice %></p>

<p>
  <strong>Guia aga o fa:</strong>
  <%= @reception.guia_aga_o_fa %>
</p>

<p>
  <strong>Customer reference document:</strong>
  <%= @reception.customer_reference_document %>
</p>

<p>
  <strong>Recepcion backup document:</strong>
  <%= @reception.recepcion_backup_document %>
</p>

<p>
  <strong>Start unload:</strong>
  <%= @reception.start_unload %>
</p>

<p>
  <strong>Finish unload:</strong>
  <%= @reception.finish_unload %>
</p>

<p>
  <strong>Digitation date:</strong>
  <%= @reception.digitation_date %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @reception.origin %>
</p>
<p>
  <strong>Reception observation:</strong>
  <%= @reception.reception_observation %>
</p>

<p>
  <strong>Rrp observation:</strong>
  <%= @reception.rrp_observation %>
</p>

<p>
  <strong>Reception order observation:</strong>
  <%= @reception.reception_order_observation %>
</p>

<p>
  <strong>Container seal:</strong>
  <%= @reception.container_seal %>
</p>

<p>
  <strong>Recepcion order date:</strong>
  <%= @reception.recepcion_order_date %>
</p>

<p>
  <strong>Reception order backup document:</strong>
  <%= @reception.reception_order_backup_document %>
</p>

<p>
  <strong>Ctnr code:</strong>
  <%= @reception.ctnr_code %>
</p>

<%= link_to 'Edit', edit_reception_path(@reception) %> |
<%= link_to 'Back', receptions_path %>




<p id="notice"><%= notice %></p>

<div class="emp-profile">

        <div class="row">

            <div class="col-md-12">
                <div class="profile-head">
                  <h5>
                      RRP: <%= @reception.rrp_number %>
                  </h5>
                  <h5>
                      RE: <%= @reception.reception_number %>
                  </h5>
                  <h5>
                      OR: <%= @reception.recepcion_order_number %>
                  </h5>
                  <h6>
                      <%= "#{@reception.customer.client_code} - #{@reception.warehouse.name}" %>
                  </h6>
                  <p class="proile-rating">CUMPLIMIENTO : <span> Dias</span></p>
                  <ul class="nav nav-tabs" id="myTab" role="tablist">
                      <li class="nav-item">
                          <a class="nav-link active" id="products-tab" data-toggle="tab" href="#products" role="tab" aria-controls="products" aria-selected="true">Productos</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">General EN</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" id="op-tab" data-toggle="tab" href="#op" role="tab" aria-controls="op" aria-selected="false">General OP</a>
                      </li>
                  </ul>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="products" role="tabpanel" aria-labelledby="products-tab">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="table-responsive">
                                          
                                          <table class="table table-striped table-sm">
                                            <thead>
                                              <tr>
                                                <th>SKU</th>
                                                <th>Nombre</th>
                                                <th>Cantidad</th>
                                                <th>Lote</th>
                                              </tr>
                                            </thead>

                                            <tbody>
                                              <% @reception_products.each do |reception_product| %>
                                                <tr>
                                                  <td><%= link_to reception_product.product.product_code, product_path(reception_product.product) %></td>
                                                  <td><%= link_to reception_product.product.name, product_path(reception_product.product) %></td>
                                                  <td><%= reception_product.quantity %></td>
                                                  <td><%= reception_product.lot_code %></td>
 
                                              <% end %>
                                            </tbody>
                                            <tfoot>
                                              <tr>
                                                <th><%= "#{@reception_products.count} Lineas" if @reception_products.count > 1 %></th>
                                                <th>Total</th>
                                                <th><%= @reception_products.sum(:quantity) %></th>
                                                <th></th>
                                              </tr>
                                            </tfoot>
                                          </table>
                                          
                                        </div>
                                    </div>

                                </div>
                                
                    </div>
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Salida CD</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>aaa</p>
                                    </div>
                                </div>


                    </div>


                    <div class="tab-pane fade" id="op" role="tabpanel" aria-labelledby="op-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Numero OP</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>aa</p>
                                    </div>
                                </div>



                    </div>
                </div>
            </div>
        </div>
         
</div>