config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :receptions
  resources :delivered_orders
  resources :custmer_client_addresses
  resources :customer_clients
  resources :countries do
    resources :regions do 
      resources :communes
    end
  end
  get 'reports/warehouse', to: "reports#warehouse", as: "warehouse_report"
  get 'reports/weekly_delivered_orders', to: "reports#weekly_delivered_orders", as: "weekly_delivered_orders_report"
  resources :stocks
  resources :warehouse_locations
  resources :warehouses
	root to: "products#sku_finder"

  ##imports
  post "import_customers", to: "customers#import_agunsa_customers", as: "import_agunsa_customers"
  post "import_agunsa_products", to: "products#import_agunsa_products", as: "import_agunsa_products"
  post "import_agunsa_warehouses", to: "warehouses#import_agunsa_warehouses", as: "import_agunsa_warehouses"
  post "import_agunsa_warehouse_locations", to: "warehouse_locations#import_agunsa_warehouse_locations", as: "import_agunsa_warehouse_locations"
  post "import_agunsa_stock", to: "stocks#import_agunsa_stock", as: "import_agunsa_stock"
  post "import_agunsa_delivered_orders", to: "delivered_orders#import_agunsa_delivered_orders", as: "import_agunsa_delivered_orders"
  post "import_agunsa_receptions", to: "receptions#import_agunsa_receptions", as: "import_agunsa_receptions"

  resources :products

  resources :customers do
  	collection do
  	end
  end

  get "sku_finder", to: "products#sku_finder", as: "sku_finder"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
  has_many :communes, dependent: :destroy
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy, :index, :new, :create]
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = @country.regions.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
    @communes = @region.communes.all
  end

  # GET /regions/new
  def new
    @region = @country.regions.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = @country.regions.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to country_region_path(@country,@region), notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to country_region_path(@country,@region), notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to country_regions_path(@country), notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:country_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = @country.regions.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def region_params
      params.require(:region).permit(:name, :sil_code)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: [@country, region], local: true) do |form| %>
  <% if region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
        <% region.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country_id %>
    <%= @country.name %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :sil_code %>
    <%= form.text_field :sil_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Show', country_region_path(@country, @region) %> |
<%= link_to 'Back', country_path(@country) %>

app/views/regions/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Inicio</a></li>
    <li class="breadcrumb-item active">Regiones</li>
  </ol>
</nav>

<p id="notice"><%= notice %></p>

<h1>Regions</h1>

<div class="table-responsive">
  <table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>País</th>
      <th>Nombre</th>
      <th>Codigo SIL</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= link_to region.country.name,  %></td>
        <td><%= region.name %></td>
        <td><%= region.sil_code %></td>
        <td><%= link_to 'Ver', region %>
        <%= link_to 'Editar', edit_region_path(region) %>
        <%= link_to 'Borrar', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Region', new_country_region_path(@country) %>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form', region: @region %>

<%= link_to 'Back', country_path(@region.country) %>

app/views/regions/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Inicio', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Paises', countries_path %></li>
    <li class="breadcrumb-item"><%= link_to @country.name, country_path(@country) %></li>
    <li class="breadcrumb-item active"><%= @region.name %></li>
  </ol>
</nav>


<p id="notice"><%= notice %></p>

  <h1><%= @region.name %></h1>


<p>
  <strong>Sil code:</strong>
  <%= @region.sil_code %>
</p>
<br>


<h2>Coumunas</h2>
<%= link_to 'Nueva Comuna', new_country_region_commune_path(@country,  @region) %>


<div class="table-responsive">
  <table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Codigo SIL</th>

    </tr>
  </thead>

  <tbody>
    <% @communes.each do |commune| %>
      <tr>
        <td><%= commune.name %></td>
        <td><%= commune.sil_code %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>