config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :receptions
  resources :delivered_orders
  resources :custmer_client_addresses
  resources :customer_clients
  resources :countries do
    resources :regions do 
      resources :communes
    end
  end
  get 'reports/warehouse', to: "reports#warehouse", as: "warehouse_report"
  get 'reports/weekly_delivered_orders', to: "reports#weekly_delivered_orders", as: "weekly_delivered_orders_report"
  resources :stocks
  resources :warehouse_locations
  resources :warehouses
	root to: "products#sku_finder"

  ##imports
  post "import_customers", to: "customers#import_agunsa_customers", as: "import_agunsa_customers"
  post "import_agunsa_products", to: "products#import_agunsa_products", as: "import_agunsa_products"
  post "import_agunsa_warehouses", to: "warehouses#import_agunsa_warehouses", as: "import_agunsa_warehouses"
  post "import_agunsa_warehouse_locations", to: "warehouse_locations#import_agunsa_warehouse_locations", as: "import_agunsa_warehouse_locations"
  post "import_agunsa_stock", to: "stocks#import_agunsa_stock", as: "import_agunsa_stock"
  post "import_agunsa_delivered_orders", to: "delivered_orders#import_agunsa_delivered_orders", as: "import_agunsa_delivered_orders"
  post "import_agunsa_receptions", to: "receptions#import_agunsa_receptions", as: "import_agunsa_receptions"

  resources :products

  resources :customers do
  	collection do
  	end
  end

  get "sku_finder", to: "products#sku_finder", as: "sku_finder"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

	before_save :calculate_item_values

	belongs_to :customer
	has_many :stocks


	def self.import_agunsa_products(customer)

		products = AgunsaManager::GetProducts.call(customer.client_code)
					products.each do |product_info|
				Product.where(
			            customer_id: customer.id,
			            product_code: product_info['codigo_producto'].tr(" ", "")
			      ).first_or_initialize do |product|
				product.name = product_info['nombre']
				product.super_family =  product_info['nombre_superfamilia_cliente']
				product.family =  product_info['nombre_familia_cliente']
				product.sub_family =  product_info['nombre_subfamilia_cliente']
				product.liters = product_info['litros_producto'].to_f
				product.weight = product_info['kilos_caja'].to_f
				product.height = product_info['alto_caja'].to_f
				product.width = product_info['ancho_caja'].to_f
				product.depth = product_info['largo_caja'].to_f
				product.units_per_box = product_info['unidades_por_caja'].to_i
				product.items_per_box = product_info['unidades_por_caja'].to_i
				product.state = "ACTIVO"
				product.boxes_per_pallet_floor = product_info['cajas_por_pata'].to_i
				product.floors_per_pallet = product_info['patas_por_pallet'].to_i
				product.boxes_per_pallet = product_info['cajas_por_pallet'].to_i
				product.unit_type = product_info['unidad']
				product.customer_price = product_info['valor_cliente']
				product.alternative_code = product_info['codigo-alternativo']
				product.save
			end
		end

	end



	private

	def calculate_item_values
		box_volume = self.height * self.width * self.depth / 1000000000
		cubic_side = box_volume ** (1/3) 
		self.box_volume = box_volume
		self.item_height = cubic_side
		self.item_width = cubic_side
		self.item_depth = cubic_side

		if self.units_per_box == 0
			self.item_weight = 0
		else
			self.item_weight = self.weight/self.units_per_box
		end
		
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @products = @products.where("product_code LIKE ?", "%"+params[:sku]+"%") if params[:sku].present?
    @products = @products.where(customer_id: params[:customer_id]) if params[:customer_id].present?
    @products = @products.where(units_per_box: params[:units_per_box]) if params[:units_per_box].present?
    @products = @products.where("name ILIKE ?", "%"+params[:name]+"%") if params[:name].present?

    @products = @products.where("weight ILIKE ?", "%"+params[:weight]+"%") if params[:weight].present?
    @products = @products.where("width ILIKE ?", "%"+params[:width]+"%") if params[:width].present?
    @products = @products.where("height ILIKE ?", "%"+params[:height]+"%") if params[:height].present?
    @products = @products.where("depth ILIKE ?", "%"+params[:depth]+"%") if params[:depth].present?


    @products = @products.order(name: :desc).paginate(page: params[:page], per_page: 50)

  end

  def sku_finder

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @stocks = @product.stocks
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Producto Creado Correctamente.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Producto Guardado Correctamente.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def import_agunsa_products
    @customer = Customer.find(params[:customer_id])
    @products = AgunsaManager::GetProducts.call(@customer.client_code)
    @products.each do |product_info|
      Product.where(
            customer_id: @customer.id,
            product_code: product_info['codigo_producto'].tr(" ", "")
      ).first_or_initialize do |product|
        product.name = product_info['nombre']
        product.super_family =  product_info['nombre_superfamilia_cliente']
        product.family =  product_info['nombre_familia_cliente']
        product.sub_family =  product_info['nombre_subfamilia_cliente']
        product.liters = product_info['litros_producto'].to_f
        product.weight = product_info['kilos_caja'].to_f
        product.height = product_info['alto_caja'].to_f
        product.width = product_info['ancho_caja'].to_f
        product.depth = product_info['largo_caja'].to_f
        product.units_per_box = product_info['unidades_por_caja'].to_i
        product.items_per_box = product_info['unidades_por_caja'].to_i
        product.state = "ACTIVO"
        product.boxes_per_pallet_floor = product_info['cajas_por_pata'].to_i
        product.floors_per_pallet = product_info['patas_por_pallet'].to_i
        product.boxes_per_pallet = product_info['cajas_por_pallet'].to_i
        product.unit_type = product_info['unidad']
        product.customer_price = product_info['valor_cliente']
        product.alternative_code = product_info['codigo-alternativo']
        product.save
      end
    end

  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Producto Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:customer_id, :product_code, :name, :super_family, :family, :sub_family, :is_expire, :liters, :state, :units_per_box, :weight, :height, :width, :depth, :boxes_per_pallet, :boxes_per_pallet_floor)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    
    <div class="col-12">
      <div class="form-group">
        <%= form.label :customer_id %>
        <%= form.collection_select :customer_id, Customer.order(name: :asc), :id, :name, {include_blank: false}, class: "form-control" %>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group">
        <%= form.label :product_code, "Codigo Producto" %>
        <%= form.text_field :product_code, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :name, "Nombre" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :super_family, "Super Familia" %>
        <%= form.text_field :super_family, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :family, "Familia" %>
        <%= form.text_field :family, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :sub_family, "SubFamilia" %>
        <%= form.text_field :sub_family, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="field">
        <%= form.label :is_expire, "¿Expira?" %>
        <%= form.check_box :is_expire %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :liters, "Litros" %>
        <%= form.text_field :liters, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :state, "Estado" %>
        <%= form.text_field :state, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :units_per_box, "Unidades por caja" %>
        <%= form.text_field :units_per_box, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :weight, "Peso (Kg)" %>
        <%= form.text_field :weight, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :height, "Alto (cm)" %>
        <%= form.text_field :height, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :width, "Ancho (cm)" %>
        <%= form.text_field :width, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :depth, "Largo (cm)" %>
        <%= form.text_field :depth, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :boxes_per_pallet, "Cajas por pallet" %>
        <%= form.text_field :boxes_per_pallet, class: "form-control" %>
      </div>
    </div>

    <div class="col-6">
      <div class="form-group">
        <%= form.label :boxes_per_pallet_floor, "Cajas por pata" %>
        <%= form.text_field :boxes_per_pallet_floor, class: "form-control" %>
      </div>
    </div>


  </div>


  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Cancelar', sku_finder_path, class: "btn btn-danger" %>

app/views/products/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Inicio', root_path %></li>
    <li class="breadcrumb-item active">Productos</li>
  </ol>
</nav>

<p id="notice"><%= notice %></p>


<h2>Productos</h2>


<%= form_tag(products_path, method: :get) do %>
  <div class="row">
    <div class="col-2">
      <%= select_tag 'customer_id', options_for_select(Customer.all.order(name: :asc).collect{ |u| [u.name, u.id] }, selected: params[:customer_id]), :prompt => "TODOS", class: "form-control" %>
    </div>
    <div class="col-2">
      <%= text_field_tag 'sku', params[:sku], placeholder: "SKU", class: "form-control" %>
    </div>
    <div class="col-2">
      <%= text_field_tag 'name', params[:name], placeholder: "Nombre", class: "form-control" %>
    </div>
  
  </div>
  <div class="row">
    <div class="col-3">
      <%= submit_tag "BUSCAR", class:"btn btn-sm btn-info" %>
    </div>
  </div>
<br>
<% end %>

<div class="table-responsive">

  <table class="table table-striped">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>SKU</th>
      <th>Nombre</th>
      <th>Unidades por caja</th>
      <th>Peso</th>
      <th>Alto(mm)</th>
      <th>Ancho(mm)</th>
      <th>Largo(mm)</th>
      <th>CXP</th>
      <th>PXP</th>
      <th>PALLET</th>
      <th>Ubicaciones</th>
      <th>Cantidad</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.customer.client_code, customer_path(product.customer_id) %></td>
        <td><%= link_to product.product_code, product %></td>
        <td><%= product.name %></td>
        <td><%= product.units_per_box %></td>
        <td><%= product.weight %> Kg</td>
        <td><%= product.height %></td>
        <td><%= product.width %></td>
        <td><%= product.depth %></td>
        <td><%= product.boxes_per_pallet_floor %></td>
        <td><%= product.floors_per_pallet %></td>
        <td><%= product.boxes_per_pallet %></td>
        <td><%= product.stocks.count %></td>
        <td><%= product.stocks.sum(:quantity) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

</div>
<div class="row">
  <div class="col">
    <%= will_paginate @products %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Inicio', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Clientes', customers_path %></li>
    <li class="breadcrumb-item"><%= link_to @product.customer.client_code, customer_path(@product.customer) %></li>
    <li class="breadcrumb-item"><%= link_to 'Productos', products_path({customer_id: @product.customer_id}) %></li>
    <li class="breadcrumb-item active"><%= @product.name %></li>
  </ol>
</nav>

<p id="notice"><%= notice %></p>

<%= link_to 'Editar', edit_product_path(@product), class: "btn btn-sm btn-warning" %> |
<%= link_to 'Volver', sku_finder_path, class: "btn btn-sm btn-info" %>



<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>Cliente</th>
        <th>Codigo</th>
        <th>Nombre</th>
        <th>Super Familia</th>
        <th>Familia</th>
        <th>Sub Familia</th>
        <th>Expira?</th>
        <th>Litros</th>
        <th>Estado</th>
        <th>UxC</th>
        <th>Peso (Kg)</th>
        <th>Alto</th>
        <th>Ancho</th>
        <th>Largo</th>
        <th>Cajas Pata</th>
        <th>Patas</th>
        <th>Cajas Pallet</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to @product.customer.client_code, customer_path(@product.customer) %></td>
        <td><%= @product.product_code %></td>
        <td><%= @product.name %></td>
        <td><%= @product.super_family %></td>
        <td><%= @product.family %></td>
        <td><%= @product.sub_family %></td>
        <td><%= @product.is_expire %></td>
        <td><%= @product.liters %></td>
        <td><%= @product.state %></td>
        <td><%= @product.units_per_box %></td>
        <td><%= @product.weight %></td>
        <td><%= @product.height %></td>
        <td><%= @product.width %></td>
        <td><%= @product.depth %></td>
        <td><%= @product.boxes_per_pallet_floor %></td>
        <td><%= @product.floors_per_pallet %></td>
        <th><%= @product.boxes_per_pallet %></th>

      </tr>
    </tbody>
  </table>
</div>




<h2>Ubicaciones</h2>

<div class="table-responsive">
  <table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Ubicacion</th>
      <th>Codigo</th>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Entrando</th>
      <th>Saliendo</th>
      <th>Bloqueada</th>
      <th>Lote</th>
      <th>Elaboracion Lote</th>
      <th>Vencimiento Lote</th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= link_to stock.warehouse_location.name, warehouse_location_path(stock.warehouse_location) %></td>
        <td><%= link_to stock.product.product_code, product_path(stock.product) %></td>
        <td><%= link_to stock.product.name, product_path(stock.product) %></td>
        <td><%= stock.quantity %></td>
        <td><%= stock.incoming_quantity %></td>
        <td><%= stock.outgoing_quantity %></td>
        <td><%= stock.blocked_quantity %></td>
        <td><%= stock.lot_code %></td>
        <td><%= stock.lot_elaboration_date %></td>
        <td><%= stock.lot_expiration_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/products/sku_finder.html.erb
<h2>Buscar Producto</h2>

<%= form_tag "/products", method: :get do  %>

	<div class="form-group">
	    <label>SKU</label>
	    <%= text_field_tag "sku", "", class:"form-control" %>
	</div>
	<%= submit_tag "Buscar", class:"btn btn-sm btn-info" %>

<% end %>