config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :receptions
  resources :delivered_orders
  resources :custmer_client_addresses
  resources :customer_clients
  resources :countries do
    resources :regions do 
      resources :communes
    end
  end
  get 'reports/warehouse', to: "reports#warehouse", as: "warehouse_report"
  get 'reports/weekly_delivered_orders', to: "reports#weekly_delivered_orders", as: "weekly_delivered_orders_report"
  resources :stocks
  resources :warehouse_locations
  resources :warehouses
	root to: "products#sku_finder"

  ##imports
  post "import_customers", to: "customers#import_agunsa_customers", as: "import_agunsa_customers"
  post "import_agunsa_products", to: "products#import_agunsa_products", as: "import_agunsa_products"
  post "import_agunsa_warehouses", to: "warehouses#import_agunsa_warehouses", as: "import_agunsa_warehouses"
  post "import_agunsa_warehouse_locations", to: "warehouse_locations#import_agunsa_warehouse_locations", as: "import_agunsa_warehouse_locations"
  post "import_agunsa_stock", to: "stocks#import_agunsa_stock", as: "import_agunsa_stock"
  post "import_agunsa_delivered_orders", to: "delivered_orders#import_agunsa_delivered_orders", as: "import_agunsa_delivered_orders"
  post "import_agunsa_receptions", to: "receptions#import_agunsa_receptions", as: "import_agunsa_receptions"

  resources :products

  resources :customers do
  	collection do
  	end
  end

  get "sku_finder", to: "products#sku_finder", as: "sku_finder"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

  # GET /warehouses
  # GET /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1
  # GET /warehouses/1.json
  def show
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses
  # POST /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to @warehouse, notice: 'Warehouse was successfully created.' }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1
  # PATCH/PUT /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to @warehouse, notice: 'Warehouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1
  # DELETE /warehouses/1.json
  def destroy
    @warehouse.destroy
    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: 'Warehouse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_agunsa_warehouses
    @warehouses = AgunsaManager::GetWarehouses.call()
    Warehouse.import_agunsa_warehouses(@warehouses)
    
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warehouse_params
      params.require(:warehouse).permit(:customer_id, :name)
    end
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse, local: true) do |form| %>
  <% if warehouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.collection_select :customer_id, Customer.order(name: :asc), :id, :name, {include_blank: false}, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Editing Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Show', @warehouse %> |
<%= link_to 'Back', warehouses_path %>

app/views/warehouses/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'inicio', root_path %></li>
    <li class="breadcrumb-item active">Bodegas</li>
  </ol>
</nav>


<p id="notice"><%= notice %></p>

<h2>Bodegas</h2>
<%= link_to 'Actualizar Bodegas', import_agunsa_warehouses_path, method: :post, class:"btn btn-sm btn-warning" %>
<%= link_to 'Nueva Bodega', new_warehouse_path, class:"btn btn-sm btn-warning" %>

<div class="table-responsive">
  <table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Name</th>
      <th>Locations</th>
    </tr>
  </thead>

  <tbody>
    <% @warehouses.each do |warehouse| %>
      <tr>
        <td><%= link_to warehouse.customer.client_code, customer_path(warehouse.customer) %></td>
        <td><%= link_to warehouse.name, warehouse_path(warehouse) %></td>
        <td><%= warehouse.warehouse_locations.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/warehouses/new.html.erb
<h1>New Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Back', warehouses_path %>

app/views/warehouses/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'inicio', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'inicio', warehouses_path %></li>
    <li class="breadcrumb-item active"><%= @warehouse.name %></li>
  </ol>
</nav>



<p id="notice"><%= notice %></p>

<%= link_to 'Importar Ubicaciones', import_agunsa_warehouse_locations_path(warehouse_id: @warehouse.id), method: :post, class:"btn btn-sm btn-warning" %>


  <h1><%= @warehouse.customer.client_code %></h1>

  <h2><%= @warehouse.name %></h2>

  <p>Ubicaciones: <%= link_to @warehouse.warehouse_locations.count, warehouse_locations_path({warehouse_id: @warehouse.id}) %></p>